name: 'Build'

on:
  workflow_call:
    inputs:
      gcp_ar_repo:
        description: "Specify team specific artifact registry repository if need to"
        type: string
        required: false
        default: "mt-images"

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get ARTIFACT_NAME from repository name
        run: echo "ARTIFACT_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - name: Potentially get the tag
        id: tagName
        uses: little-core-labs/get-git-tag@v3.0.1
        with:
          tagRegexGroup: 1

      - name: Conditional to set RELEASE to tag value
        if: ${{ startsWith(steps.tagName.outputs.tag,'v') }}
        run: echo "RELEASE=${{ steps.tagName.outputs.tag}}" >> $GITHUB_ENV

      - name: Conditional to set RELEASE to tag to latest
        if: ${{ !startsWith(steps.tagName.outputs.tag,'v') }}
        run: echo "RELEASE=latest" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.3.1'
        with:
          token_format: access_token
          create_credentials_file: true
          workload_identity_provider: projects/799884623953/locations/global/workloadIdentityPools/gh-actions/providers/github
          service_account: artifacts-wi-sa-github-actions@artifacts-352708.iam.gserviceaccount.com

      - id: docker_login
        name: Login to GAR
        uses: 'docker/login-action@v1'
        with:
          registry: 'europe-north1-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: Build
        uses: crossplane-contrib/xpkg-action@v0.2.0
        with:
          channel: master
          version: current
          command: build configuration -f ./package --name=${{ env.ARTIFACT_NAME }}.xpkg

      - name: Push Package to GitHub Container Registry
        uses: crossplane-contrib/xpkg-action@v0.2.0
        with:
          command: push configuration -f ./package/${{ env.ARTIFACT_NAME}}.xpkg ghcr.io/mattilsynet/${{ env.ARTIFACT_NAME }}:${{ env.RELEASE }}

      - name: Push Package to Google Artifact Registry
        uses: crossplane-contrib/xpkg-action@v0.2.0
        with:
          command: push configuration -f ./package/${{ env.ARTIFACT_NAME }}.xpkg europe-north1-docker.pkg.dev/artifacts-352708/${{ inputs.gcp_ar_repo }}/${{ env.ARTIFACT_NAME }}:${{ env.RELEASE }}
