name: 'Conftest'

on:
  workflow_call:
    inputs:
      paths_to_check:
        required: true
        type: string
      namespaces:
        description: "Supply namespaces if need run only specific ones"
        required: false
        default: "--all-namespaces" # or "-n <namespace1> -n <namespace2> ..."
        type: string
env:
  CONFTEST_VERSION: 0.32.1

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: Mattilsynet/map-policies
          path: map-policies
          token: ${{ secrets.token }}

      - name: Show layout
        run: ls -al

      - name: Install conftest
        run: |
          wget -O - 'https://github.com/open-policy-agent/conftest/releases/download/v${{ env.CONFTEST_VERSION }}/conftest_${{ env.CONFTEST_VERSION }}_Linux_x86_64.tar.gz' | tar zxvf -
          ./conftest --version

      - name: Conftest run
        run: ./conftest test ${{ inputs.paths_to_check }} -p map-policies/policies ${{ inputs.namespaces}} -o github
