name: Publish docker image

on:
  workflow_call:
    inputs:
      build_args:
        description: Build time arguments
        type: string
        default: ""
        required: false
      gar_image:
        description: The image path to publish to GAR
        type: string
        default: false
        required: false
      gh_image:
        description: The image path to publish to Github
        type: string
        default: false
        required: false
      push_to_gh:
        description: Publish to Github
        type: boolean
        default: false
        required: false
      push_to_gar:
        description: Publish to GAR
        type: boolean
        default: false
        required: false
    secrets:
      GAR_JSON_KEY:
        required: false

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        if: ${{ inputs.push_to_gh }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to Github
        if: ${{ inputs.push_to_gh }}
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          build-args: ${{ inputs.build_args }}
          tags: |
            ghcr.io/${{ inputs.gh_image }}

      - name: Login to Google Artifact Registry
        if: ${{ inputs.push_to_gar }}
        uses: docker/login-action@v1
        with:
          registry: europe-north1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Build and push to GAR
        if: ${{ inputs.push_to_gar }}
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          build-args: ${{ inputs.build_args }}
          tags: |
            europe-north1-docker.pkg.dev/${{ inputs.gar_image }}
