name: Build a gradle project

on:
  workflow_call:
    inputs:
      gradle_version:
        description: The gradle version to use
        type: string
        required: true
      java_version:
        description: The java version to use
        type: string
        required: true
      sonarcloud_project_id:
        description: The sonarcloud project key
        type: string
        required: false
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: ${{ inputs.java_version }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ inputs.gradle_version }}

      - name: Execute gradle build
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Publish data to sonarcloud
        if: inputs.sonarcloud_project_id
        run: ./gradlew build sonarqube -Dsonar.organization=mattilsynet -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=${{ inputs.sonarcloud_project_id }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
